// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0FnfG8oprfOLngQ5_xj1gcAUW0WIiSjI',
    appId: '1:379085914708:web:8bfa743c36b8de9df063c1',
    messagingSenderId: '379085914708',
    projectId: 'mini-project-alterra-sib-5',
    authDomain: 'mini-project-alterra-sib-5.firebaseapp.com',
    storageBucket: 'mini-project-alterra-sib-5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPHWgPew1oQt7oUTsco0omJBZ58LA4_qo',
    appId: '1:379085914708:android:1a416a2c3e572388f063c1',
    messagingSenderId: '379085914708',
    projectId: 'mini-project-alterra-sib-5',
    storageBucket: 'mini-project-alterra-sib-5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-d944hVKjc22z-2sm8gVt0d8TH7U3v8w',
    appId: '1:379085914708:ios:21470d94bed17b5ef063c1',
    messagingSenderId: '379085914708',
    projectId: 'mini-project-alterra-sib-5',
    storageBucket: 'mini-project-alterra-sib-5.appspot.com',
    iosBundleId: 'com.example.miniProjectFlutterAlterraSib5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-d944hVKjc22z-2sm8gVt0d8TH7U3v8w',
    appId: '1:379085914708:ios:6fd017869db43856f063c1',
    messagingSenderId: '379085914708',
    projectId: 'mini-project-alterra-sib-5',
    storageBucket: 'mini-project-alterra-sib-5.appspot.com',
    iosBundleId: 'com.example.miniProjectFlutterAlterraSib5.RunnerTests',
  );
}
